services:
  tw-stock-webpage:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tw-stock-webpage
    ports:
      - "8501:8501"
    volumes:
      - ../logs:/app/logs
    environment:
      - TZ=Asia/Taipei
    restart: unless-stopped
