services:
  tw-stock-webpage:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: nk7260ynpa/tw-stock-webpage:latest
    container_name: tw-stock-webpage
    ports:
      - "7938:8000"
    volumes:
      - ../logs:/app/logs
    environment:
      - TZ=Asia/Taipei
    networks:
      - db_network
    restart: unless-stopped

networks:
  db_network:
    external: true
